### ISSUE TITLE
How to replicate the results posted in the readme?

### ISSUE THREAD

**Issue by new5558** [mrpeerat/Thai-Sentence-Vector-Benchmark#1]
First I would like to say that I very much appreciate your generosity to share the findings on this repo and demonstrate the usefulness of sentence embedding in the [conference](https://www.facebook.com/groups/thainlp/posts/1456948314686654/).

I try to train other models (WangChanBERTA) with SimCSE for sentence embedding in my project. So I followed this repo and managed to train my custom SimCSE-WangChanBERTA model. Next, I would like to evaluate my model to compare model performance, so I tried to run [SimCSE-Thai.ipynb](https://github.com/mrpeerat/Thai-Sentence-Vector-Benchmark/blob/main/SimCSE-Thai.ipynb) to measure my result and compare it to the one posted on the repo's readme.

I cannot find the full code for evaluation on the repo, so I tried to make modifications with `SimCSE-Thai.ipynb` in my Colab notebook https://colab.research.google.com/drive/1lqhpfv5fPwuUDK5Ofl3AJdGpYeqBmbQ3?usp=sharing and managed to obtain the results. However, the result I found is not the same as the one provided in the readme.

<html>
<body>

Base Model | Spearman's Correlation (*100) | Supervised? | my result - Spearman (*100)
-- | -- | -- | --
simcse-model-distil-m-bert | 38.84 |  | 33.30
simcse-model-m-bert-thai-cased | 39.26 |  | 33.45
simcse-model-roberta-base-thai | 62.60 |  | 51.90
distiluse-base-multilingual-cased-v2 | 63.50 | ✔️| -
paraphrase-multilingual-mpnet-base-v2 | 80.11 | ✔️| -

</body>
</html>

Could you please guide me on what I did wrong in the evaluation process?

**Comment by mrpeerat** [comment]
First of all, thank you for your interest.
1. The evaluation code is here: https://github.com/mrpeerat/Thai-Sentence-Vector-Benchmark/blob/main/SentEval.ipynb
2. For the SentEval library, I used SimCSE's SentEval: https://github.com/princeton-nlp/SimCSE/tree/main/SentEval. But, I replace SentEval's STS benchmark test set with my STS dataset (https://github.com/mrpeerat/Thai-Sentence-Vector-Benchmark/blob/main/sts-test_th.csv).
3. Actually we can use sentence-transformer evaluation: https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/evaluation/EmbeddingSimilarityEvaluator.py (easier than SentEval and get the same result)

**Comment by mrpeerat** [comment]
I just updated the new evaluation (easy-2-implement version). Please see https://github.com/mrpeerat/Thai-Sentence-Vector-Benchmark/blob/main/STS_Evaluation/Easy_Evaluation.ipynb
